trigger:
  branches:
    include:
      - main

stages:
- stage: Dev
  jobs:
  - job: TerraformPlan
    steps:
    
    - script: 'terraform version' 
      displayName: 'Terraform Version'

    - script: 'terraform -chdir=main/ init'
      displayName: 'Init'
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

    - script: 'terraform -chdir=main/ validate'
      displayName: 'validate'

    - script: 'terraform -chdir=main/ plan -var="ARM_CLIENT_ID=$(ARM_CLIENT_ID)" -var="ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)" -var="ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)"  -var="ARM_TENANT_ID=$(ARM_TENANT_ID)"'
      displayName: 'plan'
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)


  - job: TerraformApply
    steps:
    - script : 'terraform -chdir=main/ init -input=false'    
      displayName: 'Init'
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

    - script: 'terraform -chdir=main/ apply -auto-approve -var="ARM_CLIENT_ID=$(ARM_CLIENT_ID)" -var="ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)" -var="ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)" -var="ARM_TENANT_ID=$(ARM_TENANT_ID)"'
      displayName: 'Apply'
      env:
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)